/* DO NOT EDIT! GENERATED AUTOMATICALLY! */
#if HAVE_WINSOCK2_H
# include <winsock2.h> /* avoid mingw pollution on DATADIR */
#endif
#define PREFIX "/nix/store/j5l1qvxkqiyczqnxmb9rrqid81pn8d5s-hello"
#define EXEC_PREFIX "/nix/store/j5l1qvxkqiyczqnxmb9rrqid81pn8d5s-hello"
#define BINDIR "/nix/store/j5l1qvxkqiyczqnxmb9rrqid81pn8d5s-hello/bin"
#define SBINDIR "/nix/store/j5l1qvxkqiyczqnxmb9rrqid81pn8d5s-hello/sbin"
#define LIBEXECDIR "/nix/store/j5l1qvxkqiyczqnxmb9rrqid81pn8d5s-hello/libexec"
#define DATAROOTDIR "/nix/store/j5l1qvxkqiyczqnxmb9rrqid81pn8d5s-hello/share"
#define DATADIR "/nix/store/j5l1qvxkqiyczqnxmb9rrqid81pn8d5s-hello/share"
#define SYSCONFDIR "/nix/store/j5l1qvxkqiyczqnxmb9rrqid81pn8d5s-hello/etc"
#define SHAREDSTATEDIR "/nix/store/j5l1qvxkqiyczqnxmb9rrqid81pn8d5s-hello/com"
#define LOCALSTATEDIR "/nix/store/j5l1qvxkqiyczqnxmb9rrqid81pn8d5s-hello/var"
#define RUNSTATEDIR "/nix/store/j5l1qvxkqiyczqnxmb9rrqid81pn8d5s-hello/var/run"
#define INCLUDEDIR "/nix/store/j5l1qvxkqiyczqnxmb9rrqid81pn8d5s-hello/include"
#define OLDINCLUDEDIR "/usr/include"
#define DOCDIR "/nix/store/j5l1qvxkqiyczqnxmb9rrqid81pn8d5s-hello/share/doc/hello"
#define INFODIR "/nix/store/j5l1qvxkqiyczqnxmb9rrqid81pn8d5s-hello/share/info"
#define HTMLDIR "/nix/store/j5l1qvxkqiyczqnxmb9rrqid81pn8d5s-hello/share/doc/hello"
#define DVIDIR "/nix/store/j5l1qvxkqiyczqnxmb9rrqid81pn8d5s-hello/share/doc/hello"
#define PDFDIR "/nix/store/j5l1qvxkqiyczqnxmb9rrqid81pn8d5s-hello/share/doc/hello"
#define PSDIR "/nix/store/j5l1qvxkqiyczqnxmb9rrqid81pn8d5s-hello/share/doc/hello"
#define LIBDIR "/nix/store/j5l1qvxkqiyczqnxmb9rrqid81pn8d5s-hello/lib"
#define LISPDIR "/nix/store/j5l1qvxkqiyczqnxmb9rrqid81pn8d5s-hello/share/emacs/site-lisp"
#define LOCALEDIR "/nix/store/j5l1qvxkqiyczqnxmb9rrqid81pn8d5s-hello/share/locale"
#define MANDIR "/nix/store/j5l1qvxkqiyczqnxmb9rrqid81pn8d5s-hello/share/man"
#define PKGDATADIR "/nix/store/j5l1qvxkqiyczqnxmb9rrqid81pn8d5s-hello/share/hello"
#define PKGINCLUDEDIR "/nix/store/j5l1qvxkqiyczqnxmb9rrqid81pn8d5s-hello/include/hello"
#define PKGLIBDIR "/nix/store/j5l1qvxkqiyczqnxmb9rrqid81pn8d5s-hello/lib/hello"
#define PKGLIBEXECDIR "/nix/store/j5l1qvxkqiyczqnxmb9rrqid81pn8d5s-hello/libexec/hello"
